# Generated by Django 5.2 on 2025-04-08 14:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Varos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varosNev', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Varosok',
            },
        ),
        migrations.CreateModel(
            name='Bejelentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bejelento', models.CharField(max_length=200)),
                ('utca', models.CharField(max_length=200)),
                ('lampatestek', models.IntegerField()),
                ('datum', models.DateTimeField(default=django.utils.timezone.now)),
                ('varos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lampa_bejelentes.varos')),
            ],
            options={
                'verbose_name_plural': 'Bejelentesek',
            },
        ),
    ]
